name: 'Build'
on:
  - 'push'
  - 'pull_request'
jobs:
  linux:
    name: "Linux"
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - 'Release'
          - 'Debug'
        image:
          - 'clang-11'
          - 'clang-14'
          - 'gcc-9'
          - 'gcc-12'
    runs-on: 'ubuntu-latest'
    container:
      image: 'ghcr.io/lmichaelis/images:${{matrix.image}}'
    steps:
      - uses: 'actions/checkout@v3'
      - name: 'Configure'
        run: 'cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DZK_BUILD_EXAMPLES=ON -DZK_BUILD_TESTS=ON'
      - name: 'Build'
        run: 'cmake --build build'
      - name: 'Test'
        working-directory: 'build/'
        run: 'ctest --output-on-failure'

  macos:
    name: "MacOS"
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - '15'
        build_type: [ 'Debug', 'Release' ]
    env:
      ASAN_OPTIONS: 'detect_container_overflow=0'
    runs-on: 'macos-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'maxim-lobanov/setup-xcode@v1'
        with:
          xcode-version: '${{matrix.xcode}}'
      - name: 'Configure'
        run: 'cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DZK_BUILD_EXAMPLES=ON -DZK_BUILD_TESTS=ON'
      - name: 'Build'
        run: 'cmake --build build'
      - name: 'Test'
        working-directory: 'build/'
        run: 'ctest --output-on-failure'

  windows:
    name: "Windows"
    runs-on: 'windows-2019'
    steps:
      - uses: 'actions/checkout@v3'
        with:
          submodules: 'recursive'
      - name: 'Configure'
        shell: 'bash'
        run: 'cmake -B build -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DZK_BUILD_EXAMPLES=ON -DZK_BUILD_TESTS=ON'
      - name: 'Build'
        run: 'cmake --build build --config Release -j 2'
      - name: 'Test'
        working-directory: 'build/'
        run: 'ctest -C Release --output-on-failure'
