name: 'Build'
on: 'push'
jobs:
  linux:
    name: "Linux"
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - 'clang'
          - 'build-essential'
        build_type:
          - 'Release'
          - 'Debug'
    runs-on: 'ubuntu-latest'
    container:
      image: 'docker.io/ubuntu:latest'
    steps:
      - name: 'Dependencies'
        run: 'apt update && apt install -y git cmake ${{matrix.compiler}}'
      - uses: 'actions/checkout@v3'
      - name: 'Configure'
        run: 'cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DPHOENIX_BUILD_EXAMPLES=ON'
      - name: 'Build'
        run: 'cmake --build build'
      - name: 'Test'
        working-directory: 'build/'
        run: 'ctest --output-on-failure'

  macos:
    name: "MacOS"
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - '13'
        build_type: [ 'Debug', 'Release' ]
    env:
      ASAN_OPTIONS: 'detect_container_overflow=0'
    runs-on: 'macos-11'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'maxim-lobanov/setup-xcode@v1'
        with:
          xcode-version: '${{matrix.xcode}}'
      - name: 'Configure'
        run: 'cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DPHOENIX_BUILD_EXAMPLES=ON'
      - name: 'Build'
        run: 'cmake --build build'
      - name: 'Test'
        working-directory: 'build/'
        run: 'ctest --output-on-failure'

  windows:
    name: "Windows"
    runs-on: 'windows-2019'
    steps:
      - uses: 'actions/checkout@v3'
        with:
          submodules: 'recursive'
      - name: 'Configure'
        shell: 'bash'
        run: 'cmake -B build -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DPHOENIX_BUILD_EXAMPLES=ON'
      - name: 'Build'
        run: 'cmake --build build --config Release -j 2'
      - name: 'Test'
        working-directory: 'build/'
        run: 'ctest -C Release --output-on-failure'
